AppLasLocas/urls.py
import imp
from django.urls import path 
from AppLasLocas.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [

path ("", inicio, name = "Inicio"),
path ("about/", about, name = "About"),


############  F O R M U L A R I O S ############

path ("turnosonline/", formularioTurnosOnline, name = "TurnosOnline"),
path ("contacto/", formularioContacto, name = "Contacto"),

############# C R U D . V I S T A S . T I P O . C L A S E S #################

path ("listaservicios/", ListaServicio.as_view(), name = "VerServicios"),
path ("listaservicios/<int:pk>", DetalleServicio.as_view(), name="DetalleServicio"),
path ("listaservicios/nuevo/", CrearServicio.as_view(), name = "CrearServicio"),
path ("listaservicios/editar/<int:pk>", ActualizarServicio.as_view(), name="ActualizarServicio"),
path ("listaservicios/borrar/<int:pk>", BorrarServicio.as_view(), name="BorrarServicio"),

# B U S C A R #

path("busquedaservicios/", busquedaServicio),
path("resultados/", resultado),

#################### L O G I N . Y . L O G O U T #####################

path ("login/", iniciar_sesion, name ="Login"),
path ("logout/", LogoutView.as_view(template_name="AppLasLocas/logout.html"), name = "Logout"),


######################### R E G I S T E R . & . E D I T . U S E R ##########################

path("registro/", registro, name = "Registrarse"),
path ("editarusuario/", editarUsuario, name = "EditarUsuario"), #asociada tmb a vista cambiarFotoPerfil
path ("subirimagen/", cambiarFotoPerfil, name = "Avatar"),

########################### B L O G S ###############################

path ("infounias/", blogUnias, name = "Unias"),
path ("infofaciales/", blogTratFraciales, name = "Faciales"),
path ("infopestanias/", blogPestanias, name = "Pestanias"),

]

ProyectoLasLocas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("AppLasLocas/", include ("AppLasLocas.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AppLasLocas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Servicio (models.Model): #p/CRUD

    def __str__(self):
        return f"{self.nombre} "

    nombre = models.CharField(max_length=150)
    info = models.TextField(null = True, blank = True)
    horarios = models.TextField(null = True, blank = True)
    costo = models.TextField(null = True, blank = True)

class SolicitudTurno (models.Model): #asociado a form FormularioTurno

    def __str__(self):
        return f"Pedido de turno de: {self.nombre} "

    servicio = models.CharField(max_length=200)
    mensaje = models.TextField(null = True, blank = True)
    nombre = models.CharField(max_length=150)
    tel = models.IntegerField()
    email = models.EmailField()

class Contacto (models.Model): #asociado a form FormularioContacto

    def __str__(self):
        return f"Mensaje de: {self.nombre} "

    mensaje = models.TextField(null = True, blank = True)
    nombre = models.CharField(max_length=150)
    email = models.EmailField()
    tel = models.IntegerField()

class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to ="avatares", null = True, blank = True)

    def first(self, request):

        return self.filter(user=request.user.id)

AppLasLocas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Avatar

class FormularioTurno (forms.Form):

    Servicio = forms.IntegerField()
    Comentario = forms.CharField()
    Nombre = forms.CharField()
    Teléfono = forms.IntegerField()
    Email = forms.EmailField()

class FormularioContacto (forms.Form):

    Comentario = forms.CharField()
    Nombre = forms.CharField()
    Email = forms.EmailField()
    Teléfono = forms.IntegerField()

class FormularioRegistro(UserCreationForm): 

    Nombre = forms.CharField()
    Teléfono = forms.IntegerField()
    Fecha_de_Nacimiento = forms.DateField()
    Email = forms.EmailField()
    password1 = forms.CharField(label="Ingrese una contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repita la contraseña", widget=forms.PasswordInput)

    class Meta: 

        model = User 
        fields = ["username", "Nombre", "Fecha_de_Nacimiento", "Teléfono", "Email", "password1", "password2"]

class FormularioEditarUsuario(UserCreationForm): 

    email = forms.EmailField()
    password1 = forms.CharField(label="Ingrese una contraseña", widget=forms.PasswordInput) 
    password2 = forms.CharField(label="Repita la contraseña", widget=forms.PasswordInput)
    Teléfono = forms.IntegerField(label="Ingrese su nuevo teléfono")
    Fecha_de_Nacimiento = forms.DateField()

    class Meta:

        model = User 
        fields = ["email", "password1", "password2", "Teléfono", "Fecha_de_Nacimiento"] 

class CambiarAvatar (forms.ModelForm):

    class Meta:

        model = Avatar
        fields = ["user", "imagen"]

AppLasLocas/views.py
from django.shortcuts import render
from AppLasLocas.models import *
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from django.contrib.auth import login, logout, authenticate
from .forms import *
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView 
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

################## I N I C I O #####################

def inicio (request):

    return render (request, "AppLasLocas/inicio.html")

################# L O G I N .  R E G I S T R O . & . E D I T - U S E R ############################

def iniciar_sesion(request):

    if request.method == "POST":

        form = AuthenticationForm(request, data=request.POST) 

        if form.is_valid(): 

            usuario = form.cleaned_data.get("username") 
            contra = form.cleaned_data.get("password") 

            user = authenticate(username=usuario, password=contra)

            if user:

                login(request, user)

                return render (request, "AppLasLocas/inicio.html")
        
        else:

            return render (request, "AppLasLocas/inicio.html", {"mensaje": f"Datos inválidos!"})

    else:

        form = AuthenticationForm()

    return render (request, "AppLasLocas/login.html", {"formu3":form})

def registro (request):

    if request.method == "POST":

        formu = FormularioRegistro(request.POST)

        if formu.is_valid():

            nombreUsuario = formu.cleaned_data["username"]
            formu.save() 

            return render (request, "AppLasLocas/inicio.html", {"mensaje": f"Usuario {nombreUsuario} creado!"}) 

    else:
        
        formu = FormularioRegistro() 

    return render(request, "AppLasLocas/registro.html", {"formu4": formu})

@login_required
def editarUsuario (request):

    usuarioOnline = request.user 

    if request.method == "POST": 

        formuEditUser = FormularioEditarUsuario(request.POST) 

        if formuEditUser.is_valid(): 

            info = formuEditUser.cleaned_data 

            usuarioOnline.email = info ["email"] 
            usuarioOnline.password1 = info ["password1"] 
            usuarioOnline.password2= info ["password2"]
            usuarioOnline.Teléfono = info ["Teléfono"]
            usuarioOnline.Fecha_de_Nacimiento= info ["Fecha_de_Nacimiento"]

            usuarioOnline.save() 

            return render (request, "AppLasLocas/inicio.html") 

    else:

        formuEditUser = FormularioEditarUsuario(initial= {"email": usuarioOnline.email} ) 


    return render (request, "AppLasLocas/editarUsuario.html", {"formuEditar": formuEditUser, "usuario": usuarioOnline} )

################################# C A M B I A R . F O T O . D E . P E R F I L ##################################

@login_required
def cambiarFotoPerfil(request):

    if request.method == "POST":

        formuImagen = CambiarAvatar(request.POST, request.FILES)

        if formuImagen.is_valid():

            info = formuImagen.cleaned_data
            
            avatar = Avatar(user=request.user, imagen=info["imagen"])

            avatar.save()

            return render (request, "AppLasLocas/inicio.html")

    else:

        formImagen = CambiarAvatar()

    return render (request, "AppLasLocas/agregarImg.html", {"imagen": formImagen})


################## A B O U T . & . B L O G S ########################

def about (request):

    return render (request, "AppLasLocas/about.html")

def blogUnias (request):

    return render (request, "AppLasLocas/blogUnias.html")

def blogTratFraciales (request):

    return render (request, "AppLasLocas/blogFaciales.html")

def blogPestanias (request):

    return render (request, "AppLasLocas/blogPestanias.html")

########################  F O R M U L A R I O S #########################
@login_required
def formularioTurnosOnline (request):

    if request.method=="POST":

        formuTurno = FormularioTurno(request.POST)

        if formuTurno.is_valid():

            info = formuTurno.cleaned_data

            turno = SolicitudTurno(servicio = info ["Servicio"], mensaje = info["Comentario"], nombre = info["Nombre"], tel = info ["Teléfono"], email = info ["Email"]) 
            turno.save()

            return render (request, "AppLasLocas/inicio.html") 
            
    else:
        
        formuTurno = FormularioTurno()

    return render(request, "AppLasLocas/solicitarTurno.html", {"formuTurno":formuTurno}) 

def formularioContacto (request):

    if request.method=="POST":

        formuContacto = FormularioContacto(request.POST)

        if formuContacto.is_valid():

            info = formuContacto.cleaned_data

            datos = Contacto(mensaje = info ["Comentario"], nombre = info["Nombre"], email = info ["Email"], tel = info ["Teléfono"]) 
            datos.save()

            return render (request, "AppLasLocas/inicio.html") 
            
    else:
        
        formuContacto = FormularioContacto()

    return render(request, "AppLasLocas/contacto.html", {"formuContacto":formuContacto}) 

####################### C R U D ##########################

class ListaServicio (ListView): #Read

    model = Servicio
    template_name= "AppLasLocas/listaServicios.html"

class DetalleServicio (DetailView):

    model = Servicio

class CrearServicio (LoginRequiredMixin, CreateView): #Create

    model = Servicio
    success_url = "/AppLasLocas/listaServicios"
    fields = ["nombre", "info", "horarios", "costo"]

class ActualizarServicio (LoginRequiredMixin,UpdateView): #update

    model = Servicio
    success_url = "/AppLasLocas/listaServicios"
    fields = ["horarios","costo"]

class BorrarServicio (LoginRequiredMixin, DeleteView): #delete

    model = Servicio
    success_url = "/AppLasLocas/listaServicios"

# B U S C A R #

def busquedaServicio (request):

    return render (request, "AppCoder/listaServicios.html")

def resultado(request):

    if request.GET["nombre"]:

        busqueda = request.GET["nombre"]
        servicio = Servicio.objects.filter(nombre__icontains=busqueda) 

        return render (request, "AppLasLocas/resultados.html", {"servicio":servicio, "busqueda": busqueda})

    else:

        mensaje = "No enviaste datos."
        
        
    return render (request, "AppLasLocas/resultados.html", {"mensaje":mensaje})

AppLasLocas/templates/AppLasLocas/agregarImg.html
{% extends "AppLasLocas/padre.html" %} 

{% load static %} 

{% block titulo %} 

<form action="" method="POST" enctype="multipart/form-data"> {%csrf_token%}

    <table>

            {{imagen.as_table}}

    </table>
    <br>
    <input type="submit", value="Enviar Imagen", style="color: black">

</form> 
{% endblock %} 

AppLasLocas/templates/AppLasLocas/blogPestanias.html
{% extends "AppLasLocas/padre.html" %} 

{% load static %} 



{% block titulo %}

<!---header-wrap--->
  <div class="wrap4">
    <div class="container">
      <div class="leftcol">
        <div class="title">
          <h1>5 beneficios del lifting de pestañas</h1>
        </div>
        <p align ="right">Martes 18 de Octubre de 2022</p>
        <div class="page-content">
        <div class="panel borderbotm-none">
          <div class="content">
            <br>
            <p>Ay, el lifting de pestañas… Mentiríamos si no dijeramos que <b>es la alternativa perfecta para lucir unas pestañas infinitas.</b> No nos extraña que cada vez más y más personas reserven este tratamiento para conseguir una mirada XXL.</p>
            <p>Y es que además con el lifting se consigue un resultado de lo más natural: unas pestañas largas, definidas y llenas de volumen. Si es que cómo no nos va a encantar este tratamiento…</p>
            <br>
            <h3 id = "ref1">1. No daña tus pestañas</h3>
            <br>
            <p>El lifting de pestañas <b>es de los tratamientos menos agresivos para conseguir una mirada de cine.</b> Siempre y cuando te lo hagas en un sitio especializado, claro. El tratamiento es simple: <b>se estiran las pestañas desde la raíz y se fijan con un gel para que el resultado dure meses.</b> Y créenos cuando te decimos que en todo el proceso, tus pestañas no sufrirán lo más mínimo.</p>
            <br>
            <h3 id = "ref2">2. Se consigue más volumen</h3>
            <br>
            <p>Con el lifting, se estiran <b>incluso las pestañas más cortas.</b> Lo que aporta más volumen a tu mirada. Eso es, lucirás unas pestañas XXL allá donde vayas. ¿Y en cuanto a la máscara de pestañas? Si quieres, ¡te podrás olvidar de ella por una temporada!</p>
            <br>
            <h3 id = "ref3">3. Tratamiento express</h3>
            <br>
            <p>El proceso es de lo más sencillo. Primero pondrán unas almohadillas de silicona en tus párpados para pegar las pestañas, después pondrán el gel fijador y, tras esperar un poco para que haga efecto… <b>¡En menos de una hora tendrás unas pestañas larguísimas y llenas de personalidad!</p></b> 
            <br>
            <h3 id = "ref4">4. Resultado natural</h3>
            <br>
            <p>¿Resultado? ¡Pestañas completamente naturales! El lifting lo único que se hace es levantar las pestañas desde la raíz haciendo que parezcan más largas y densas. Así que si lo quieres mantener en secreto, <b>¡nadie descubrirá cuál es el truco!</p></b> 
            <br>
            <h3 id = "ref5">5. Larga duración</h3>
            <br>
            <p> Lo mejor es que tiene una duración de <b>aproximadamente dos meses.</b> Lo que quiere decir que en verano, si te apetece, te lo puedes hacer al principio y te aguantará hasta la vuelta de vacaciones. Perfecto para meterse en la piscina o en la playa sin preocuparte de que se te quite la máscara de pestañas. Porque con el lifting… ¡no te hará falta!</p>

            <br>
            <p>Solicita más información sobre este tratamiento haciendo <b><a href="{% url 'Contacto' %}">click aqui</a></p></b>


          </div>
        </div>
        </div>
        
      </div>
      <div class="rightcol">
        <div class="title">
          <h1>Guía</h1>
        </div>        <div class="panel">
          <div class="content">
            <ul>
              <li><a href="#ref1">No daña tus pestañas</a></li>
              <li><a href="#ref2">Más volumen</a></li>
              <li><a href="#ref3">Tratamiento express</a></li>
              <li><a href="#ref5">Resultado natural</a></li>
              <li><a href="#ref5">Larga duración</a></li>
            </ul>
          </div>
        </div>
      </div>
    <div class="clearing"></div>  
    </div>
  </div>
{% endblock %} 

AppLasLocas/templates/AppLasLocas/contacto.html
{% extends "AppLasLocas/padre.html" %} 

{% load static %}  

{% block titulo %}

<p><h1>Te invitamos a seguirnos en nuestras RRSS:</h1></p>
<br>
<h2><p><a href="https://www.instagram.com/laslocasbeauty/" target = "_blank">Instagram</a></p></h2>
<h2><p><a href="https://www.facebook.com/profile.php?id=100063446212488" target = "_blank">Facebook</a></p></h2>
<br>
<p><h2>O sino, dejanos tus datos y a la brevedad nos pondremos en contacto:</h2></p>
<br>

<form action="" method="POST"> {% csrf_token %}
<table> 

    {{formuContacto.as_p}}

</table>
<br>
<input type="submit" value="ENVIAR">

</form>


{% endblock %} 

AppLasLocas/templates/AppLasLocas/inicio.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  {% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Mi primer Sitio Web - Noelia Amador</title>
<link href="{% static 'AppLasLocas/css/styles.css' %}" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Economica' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
<!--menu-->
<link rel="stylesheet" href="{% static 'AppLasLocas/css/superfish.css' %}" media="screen">
<script src="{% static 'AppLasLocas/js/jquery-1.9.0.min.js' %}"></script>
<script src="{% static 'AppLasLocas/js/hoverIntent.js' %}"></script>
<script src="{% static 'AppLasLocas/js/superfish.js' %}"></script>
<script>

		// initialise plugins
		jQuery(function(){
			jQuery('#example').superfish({
				//useClick: true
			});
		});

		</script>
</head>

<body>


  <div class="wrap1">
    <div class="container">
      <div class="header">
        <div class="logo">
          <a href="{% url 'Inicio' %}" title="Página principal" id="logo" >
          <img src="{% static 'AppLasLocas/images/logo.png' %}" width="250" height="145" alt="image">
        </a>
        </div>
        <div style="text-align:center">    {% if request.user.is_authenticated %}
          <b><p style="color: rgb(129, 88, 252);"> Bienvenida de nuevo, {{user.username}}!</b>
            {% with first_image=user.avatar_set.last %}
              {% if first_image %}
                <img src="{{ first_image.imagen.url }}" width="40" height="40">
              {% endif %}
            {% endwith %} 
          </p>
            
          
          {% endif %}
          </div>
          <br>
    <div class="menu">
      <ul class="sf-menu" id="example">
        <li><a href={% url 'Inicio' %}>Home</a></li>
        <li><a href={% url 'VerServicios' %}>Servicios</a></li>
        <li><a href={% url 'TurnosOnline' %}>Turnos Online</a></li>
        <li><a href={% url 'Contacto' %}>Contacto</a></li>
        <li><a href={% url 'About' %}>About</a></li>

        <br>

        <!--Colocar avatar al lado del saludo de inicio de sesión y conf tamaño-->

        <br>
        <br>
        {% if request.user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'EditarUsuario' %}">Editar Usuario</a>
        <a class="btn btn-primary" href="{% url 'Logout' %}">Cerrar Sesión</a>

        {% else %}
        <br>
        <br>
        <br>
        <a class="btn btn-primary" href="{% url 'Login' %}">Iniciar Sesión</a>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class="clearing"></div>
</div>
<div class="clearing"></div>
</div>
<!---header-wrap--->
<div class="wrap2">
  <div class="container">
    {% block logueo %}
      <h2 style="text-align: center ;">{{mensaje}}</h2>
    {% endblock %}
    <br>
    <br>
    <div class="banner"> <img src="{% static 'AppLasLocas/images/bannhome.PNG' %}" alt="banner" />
      <div class="banner-shadows"></div>
    </div>
  <div class="clearing"></div>
  </div>
  </div>
  <br>
    <div class="banner-shadows"></div>
  </div>
<div class="clearing"></div>
</div>
</div>
<!---banner-wrap--->
<div class="wrap3">
  <div class="container">
    <div class="box mar-right40">
      <div class="title">
        <h1>Lifting de Pestañas</h1>
        <h2>Llevá tus mirada a un nuevo nivel...</h2>
      </div>
      <div class="content">
        <p>Sabemos que hay miradas que lo dicen todo: pueden ser seductoras, dulces e, incluso, matadoras. Uno de los detalles básicos para que éstas tengan presencia son las pestañas: mientras que muchas chicas optan por vestir los ojos con pestañas postizas, otras se decantan por una clásica máscara de pestañas. Sin embargo, en los últimos meses hay una tendencia que atrae y genera mucha curiosidad: los lifting de pestañas.</p>
        <div class="button"><a href={% url 'TurnosOnline' %}>Pedir turno</a></div>
      </div>
    </div>
    <div class="box">
      <div class="title">
        <h1>Uñas esculpidas</h1>
        <h2>Tus manos nunca estuvieron más lindas!!</h2>
      </div>
      <div class="content">
        <p>La manicura es hoy un paso clave a la rutina de belleza de todas las mujeres y afortunadamente, la innovación es tanta que los aliados para hacernos todo más fácil son cada vez más. Si hoy querés lucir unas manos con mucho estilo, las uñas esculpidas es una gran opción. Si tus uñas suelen romperse o bien si te gustaría alargarlas, las artificiales pueden ayudarte. Hay de acrílico o de gel.</p>
        <div class="button"><a href={% url 'TurnosOnline' %}>Pedir turno</a></div>
      </div>
    </div>
    <br>
    <br>
    <h3>CLICK ACÁ PARA CONOCER TODOS NUESTROS SERVICIOS!</h3>
      <div class="button"><a href={% url 'VerServicios' %}>Ver</a></div>
      <br>
      <br>
  <div class="clearing"></div>  
  </div>
</div>
<!---wrap3--->
<div class="wrap1 ">
  <div class="container">
    <div class="title">
      <h1>¿Qué dicen nuestras clientas sobre los servicios...?</h1>
    </div>
    <div class="service mar-right40"> <img src="{% static 'AppLasLocas/images/unias.jpeg' %}" width="248" height="158" alt="Uñas esculpidas" />
      <div class="shadows"></div>
      <div class="content">
        <p>Excelente!! Me duran las uñas intactas hasta el siguiente servicio, y los diseños son geniales!!</p>
        <p>Noelia, clienta de Mara.</p>
        <div class="button"><a href="{% url 'Unias' %}">+ INFO</a></div>
      </div>
    </div>
    <div class="service mar-right40"> <img src="{% static 'AppLasLocas/images/piel.jpeg' %}" width="248" height="158"  alt="Cosmetología" />
      <div class="shadows"></div>
      <div class="content">
        <p>Siento que rejuvenecí varios años, de hecho varias personas lo han notado y me lo dijeron. Estoy feliz!!.</p>
        <p>Carmen, clienta de Ludmila.</p>
        <div class="button"><a href="{% url 'Faciales' %}">+ INFO</a></div>
      </div>
    </div>
    <div class="service"> <img src="{% static 'AppLasLocas/images/lifting.jpeg' %}" width="248" height="158" alt="Lifting de Pestañas" />
      <div class="shadows"></div>
      <div class="content">
        <p>Realmente amo el Lifting de Pestañas, dura un montón, 0 doloroso y rápido de hacer. Lo recomiendo 100%!!</p>
        <p>Carla, clienta de Karen.</p>
        <div class="button"><a href="{% url 'Pestanias' %}">+ INFO</a></div>
      </div>
    </div>
  <div class="clearing"></div>  
  </div>
  <div class="clearing"></div>
</div>

<!---wrap4--->
<div class="wrap3">
<div class="container">
  <h4><p><div class="footer" style="color: white;" >Realizado por Noelia Amador. <a style="color: black ;" href="https://github.com/MNAmador92/AppLasLocas.git" target = "_blank">Link a GitHub</a></h4></p>
  
<div class="clearing"></div>
</div>
</div>
<div class="shadows2">
</div>
</body>
</html>

AppLasLocas/templates/AppLasLocas/logout.html
{% extends "AppLasLocas/padre.html" %} 

{% load static %} 

{% block titulo %} 

<p style="color: black ;"><h3>Has cerrado sesión correctamente.</p>
Gracias por tu visita ♥!</h3>
<br>
<br>
<h4><a href={% url 'Inicio' %} style="color: violet ;">HOME</a>
</h4>

{% endblock %} 

AppLasLocas/templates/AppLasLocas/padre.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  {% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Mi primer Sitio Web - Noelia Amador</title>
<link href="{% static 'AppLasLocas/css/styles.css' %}" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Economica' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
<!--menu-->
<link rel="stylesheet" href="{% static 'AppLasLocas/css/superfish.css' %}" media="screen">
<script src="{% static 'AppLasLocas/js/jquery-1.9.0.min.js' %}"></script>
<script src="{% static 'AppLasLocas/js/hoverIntent.js' %}"></script>
<script src="{% static 'AppLasLocas/js/superfish.js' %}"></script>
<script>

		// initialise plugins
		jQuery(function(){
			jQuery('#example').superfish({
				//useClick: true
			});
		});

		</script>
</head>

<body>


  <div class="wrap1">
    <div class="container">
      <div class="header">
        <div class="logo">
          <a href="{% url 'Inicio' %}" title="Página principal" id="logo" >
          <img src="{% static 'AppLasLocas/images/logo.png' %}" width="250" height="145" alt="image">
        </a>
        </div>
        <div style="text-align:center">    {% if request.user.is_authenticated %}
          <b><p style="color: rgb(129, 88, 252);"> Bienvenida de nuevo, {{user.username}}!</b>
            {% with first_image=user.avatar_set.last %}
              {% if first_image %}
                <img src="{{ first_image.imagen.url }}" width="40" height="40">
              {% endif %}
            {% endwith %} 
          </p>
            
          
          {% endif %}
          </div>
          <br>
    <div class="menu">
      <ul class="sf-menu" id="example">
        <li><a href={% url 'Inicio' %}>Home</a></li>
        <li><a href={% url 'VerServicios' %}>Servicios</a></li>
        <li><a href={% url 'TurnosOnline' %}>Turnos Online</a></li>
        <li><a href={% url 'Contacto' %}>Contacto</a></li>
        <li><a href={% url 'About' %}>About</a></li>

        <br>
        <br>
        <br>
        {% if request.user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'EditarUsuario' %}">Editar Usuario</a>
        <a class="btn btn-primary" href="{% url 'Logout' %}">Cerrar Sesión</a>

        {% else %}
        <br>
        <br>
        <br>
        <a class="btn btn-primary" href="{% url 'Login' %}">Iniciar Sesión</a>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class="clearing"></div>
</div>
<div class="clearing"></div>
</div>
<!---header-wrap--->
<div class="wrap2">
<div class="container">
  <br>
  <br>
  <br>
  {% block titulo %}

  {% endblock %}
  {% block logueo %}

  {% endblock %}

  <br>
    <div class="banner-shadows"></div>
  </div>
<div class="clearing"></div>
</div>
</div>
<!---banner-wrap--->


<!---wrap4--->
<div class="wrap3">
<div class="container">
  <h4><p><div class="footer" style="color: white;" >Realizado por Noelia Amador. <a style="color: black ;" href="https://github.com/MNAmador92/AppLasLocas.git" target = "_blank">Link a GitHub</a></h4></p>
  
<div class="clearing"></div>
</div>
</div>
<div class="shadows2">
</div>
</body>
</html>